#! /usr/bin/env python3

import sys
from time import sleep
from quick2wire.parts.pcf8591 import *
from quick2wire.i2c import I2CMaster
from vis import volt_plot

address = int(sys.argv[1]) if len(sys.argv) > 1 else BASE_ADDRESS
pin_index1 = int(sys.argv[2]) if len(sys.argv) > 2 else 0
pin_index2 = int(sys.argv[3]) if len(sys.argv) > 3 else 1

with I2CMaster() as i2c:
    adc = PCF8591(i2c, THREE_DIFFERENTIAL)
    pin1 = adc.differential_input(1)
    #pin2 = adc.single_ended_input(pin_index2)

    count = 1
    data = {}
    while True:
        print("read: {} : {}".format(count, pin1.raw_value))
        #sleep(0.1)
        count += 1
        data[count] = pin1.raw_value
        volt_plot(count, data)
